Fluxo corrigido

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -23,4 +23,30 @@ jobs:
               run: |
                 docker tag marvelnft:node "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
                 docker push "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
+
+    aplication_unit_tests:
+        runs-on: ubuntu-latest
+          
+        steps:
+          - name: Checkout
+            uses: actions/checkout@v4
+          
+          - name: Pull docker image
+            run: docker pull b0nam/marvelnft:node
+          
+          - name: Run tests on docker image
+            run: |
+              docker run marvelnft:node npm test
+              exit_code=$?
+              if [ $exit_code -eq 0 ]; then
+                echo "[+] All tests passed successfuly!"
+              else
+                echo "[-] Test failures!"
+                exit $exit_code
+              fi
+          
+          - name: Push marvelnft node
+            run: |
+              docker tag marvelnft:node "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
+              docker push "${{ secrets.DOCKERHUB_USERNAME }}/marvelnft:node"
           
